/* Generated By:JavaCC: Do not edit this line. SymbolConstants.java */
package net.weath.chords.parser;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface SymbolConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int NOTENAME = 5;
    /**
     * RegularExpression Id.
     */
    int FLAT = 6;
    /**
     * RegularExpression Id.
     */
    int SHARP = 7;
    /**
     * RegularExpression Id.
     */
    int DBLFLAT = 8;
    /**
     * RegularExpression Id.
     */
    int DBLSHARP = 9;
    /**
     * RegularExpression Id.
     */
    int DIMINISHED = 10;
    /**
     * RegularExpression Id.
     */
    int MINOR = 11;
    /**
     * RegularExpression Id.
     */
    int PERFECT = 12;
    /**
     * RegularExpression Id.
     */
    int MAJOR = 13;
    /**
     * RegularExpression Id.
     */
    int AUGMENTED = 14;
    /**
     * RegularExpression Id.
     */
    int UNISON = 15;
    /**
     * RegularExpression Id.
     */
    int SECOND = 16;
    /**
     * RegularExpression Id.
     */
    int THIRD = 17;
    /**
     * RegularExpression Id.
     */
    int FOURTH = 18;
    /**
     * RegularExpression Id.
     */
    int FIFTH = 19;
    /**
     * RegularExpression Id.
     */
    int SIXTH = 20;
    /**
     * RegularExpression Id.
     */
    int SEVENTH = 21;
    /**
     * RegularExpression Id.
     */
    int OCTAVE = 22;
    /**
     * RegularExpression Id.
     */
    int NINTH = 23;
    /**
     * RegularExpression Id.
     */
    int TENTH = 24;
    /**
     * RegularExpression Id.
     */
    int ELEVENTH = 25;
    /**
     * RegularExpression Id.
     */
    int TWELFTH = 26;
    /**
     * RegularExpression Id.
     */
    int THIRTEENTH = 27;
    /**
     * RegularExpression Id.
     */
    int FOURTEENTH = 28;
    /**
     * RegularExpression Id.
     */
    int DBLOCTAVE = 29;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
        "<EOF>",
        "\" \"",
        "\"\\r\"",
        "\"\\n\"",
        "\"\\t\"",
        "<NOTENAME>",
        "\"b\"",
        "\"#\"",
        "\"bb\"",
        "\"x\"",
        "\"diminished\"",
        "\"minor\"",
        "\"perfect\"",
        "\"major\"",
        "\"augmented\"",
        "\"unison\"",
        "\"second\"",
        "\"third\"",
        "\"fourth\"",
        "\"fifth\"",
        "\"sixth\"",
        "\"seventh\"",
        "\"octave\"",
        "\"ninth\"",
        "\"tenth\"",
        "\"eleventh\"",
        "\"twelfth\"",
        "\"thirteenth\"",
        "\"fourteenth\"",
        "\"double octave\"",
        "\"5\"",
        "\"m\"",
        "\"mi\"",
        "\"min\"",
        "\"-\"",
        "\"M\"",
        "\"ma\"",
        "\"maj\"",
        "\"aug\"",
        "\"dim\"",
        "\"o\"",
        "\"O\"",
        "\"(\"",
        "\")\"",
        "\"no root\"",
        "\"noroot\"",
        "\"no3\"",
        "\"no 3\"",
        "\"no5\"",
        "\"no 5\"",
        "\"b5\"",
        "\"#5\"",
        "\"-5\"",
        "\"+5\"",
        "\"+\"",
        "\"6\"",
        "\"7\"",
        "\"-maj7\"",
        "\"maj7\"",
        "\"M7\"",
        "\"9\"",
        "\"M9\"",
        "\"maj9\"",
        "\"-maj9\"",
        "\"b9\"",
        "\"-9\"",
        "\"#9\"",
        "\"+9\"",
        "\"b10\"",
        "\"-10\"",
        "\"11\"",
        "\"no11\"",
        "\"no 11\"",
        "\"M11\"",
        "\"maj11\"",
        "\"-maj11\"",
        "\"#11\"",
        "\"+11\"",
        "\"13\"",
        "\"maj13\"",
        "\"M13\"",
        "\"b13\"",
        "\"sus\"",
        "\"sus2\"",
        "\"sus4\"",
        "\"add2\"",
        "\"add4\"",
        "\"add6\"",
        "\"add9\"",
        "\"over\"",
        "\"2\"",
        "\"/2\"",
        "\"4\"",
        "\"/4\"",
        "\"/6\"",
        "\"/7\"",
        "\"/9\"",
        "\"/11\"",
        "\"/13\"",
        "\"inversion)\"",
        "\"/\"",
        "\"1st\"",
        "\"2nd\"",
        "\"3rd\"",
        "\"4th\"",
        "\"5th\"",
        "\"6th\"",
        "\"7th\"",
        "\"8th\"",
        "\"9th\"",
        "\"10th\"",
        "\"11th\"",
        "\"12th\"",};

}
